name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'Zeus-Includes.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "Zeus-Includes.zip"
        name: Includes
        generateReleaseNotes: true
        allowUpdates: true
        makeLatest: true
        token: ${{ secrets.GITHUB_TOKEN }}
